require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.0'

# $FirebaseSDKVersion = '6.13.0'

pod 'GoogleSignIn', '~> 5.0.2'

target 'Shopertino' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ "Flipper-Folly" => "2.5.0"})
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'

  use_unimodules!
end
