import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';
import { RFPercentage } from 'react-native-responsive-fontsize';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#02A8A8',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 30,
  },
  upperContainer: {
    //height: '10%',
    width: '100%',
    // borderWidth: 1,
    //borderBottomWidth: 0.5,
    //borderColor: '#545454',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    //paddingBottom: 10,
  },
  arrowButton: {
    marginLeft: 10,
  },
  arrowIcon: {
    height: 0.06 * width,
    width: 0.06 * width,
    tintColor: 'white',
  },
  arrowIconHidden: {
    height: 0.06 * width,
    width: 0.06 * width,
    tintColor: '#02A8A8',
  },
  titleContainer: {
    //borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleText: {
    fontSize: RFPercentage(4),
    fontWeight: 'bold',
    color: 'white',
  },
  messageContainer: {
    //flex: 2,
    // borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 10,
  },
  nameText: {
    fontSize: RFPercentage(4),
    color: 'white',
    fontWeight: 'bold',
    //textAlign: 'center',
    //marginTop: 20,
    marginBottom: 5,
  },
  messageContentContainer: {
    minHeight: 0.13 * height,
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 10,
    // flexDirection: 'row',
    // justifyContent: 'flex-start',
    alignItems: 'center',
  },
  avatarImage: {
    height: 0.25 * width,
    width: 0.25 * width,
    borderRadius: 65,
  },
  messageText: {
    // flex: 1,
    flexWrap: 'wrap',
    fontSize: RFPercentage(2.5),
    color: '#545454',
    marginLeft: 10,
  },
  itemImageContainer: {
    // borderWidth: 1,
    borderColor: 'red',
    justifyContent: 'center',
    //alignItems: 'center',
    width: '100%',
    height: '80%',
    //flex: 4,
    paddingBottom: 10,
  },
  itemImageContentContainer: {
    //width: '80%',
    //height: '30%',
    flex: 1,
    backgroundColor: 'white',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemImage: {
    height: '90%',
    width: '90%',
    //borderRadius: 10,
    resizeMode: 'contain',
    borderWidth: 1,
  },
  itemDetailsContainer: {
    // borderWidth: 1,
    width: '100%',
    //height: '40%',
    //justifyContent: 'center',
    //alignItems: 'center',
    //flex: 2,
    borderBottomWidth: 1,
    borderColor: 'white',
    paddingBottom: 5,
    marginBottom: 20,
  },
  itemTitleText: {
    fontSize: RFPercentage(3),
    fontWeight: 'bold',
    color: 'white',
    paddingVertical: 10,
  },
  itemDescriptionText: {
    fontSize: RFPercentage(2),
    color: 'white',
    paddingVertical: 5,
  },
  buttonContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderColor: 'green',
    width: '90%',
    paddingTop: '3%',
  },
  button: {
    borderRadius: 8,
    backgroundColor: 'white',
    padding: 10,
    width: '48%',
    borderWidth: 1,
    borderColor: '#42E2CD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: RFPercentage(2.5),
    fontWeight: '600',
    color: '#42E2CD',
    textAlign: 'center',
  },
  opacityButton: {
    borderRadius: 8,
    backgroundColor: 'white',
    padding: 10,
    borderWidth: 1,
    borderColor: '#42E2CD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  redeemButtonText: {
    fontSize: RFPercentage(2.5),
    fontWeight: '600',
    color: '#42E2CD',
    textAlign: 'center',
  },
  largeButton: {
    borderRadius: 8,
    backgroundColor: 'white',
    padding: 10,
    width: '90%',
    borderWidth: 1,
    borderColor: '#42E2CD',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  // video: {
  //   // width: '100%',
  //   // height: 300,
  //   marginBottom: 10,
  // },
  video: {
    minHeight: 295,
  },
  scrollView: {
    display: 'flex',
    width: '90%',
  },
  selectedMemoryImage: {
    minHeight: 295,
    // minWidth: '100%',
    resizeMode: 'contain',
    // borderWidth: 1,
    // borderColor: 'red',
  },
  paginationBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    minWidth: '100%',
    height: 18,
  },
  dot: {
    height: 10,
    borderRadius: 5,
    backgroundColor: 'white',
    margin: 3,
  },
  memoryMediaContainer: {
    marginTop: 10,
    minWidth: '100%',
    height: 300,
  },
  wrappedGift: {
    marginTop: 10,
    minWidth: '100%',
    height: 300,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 20,
  },
  wrappedGift_image: {
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#42E2CD',
  },
  wrappedGift_nameTag: {
    backgroundColor: 'white',
    borderWidth: 4,
    borderColor: '#42E2CD',
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 30,
  },
  wrappedGift_nameText: {
    fontSize: RFPercentage(4),
    fontWeight: 'bold',
  },
  wrappedGift_subText: {
    fontSize: RFPercentage(3),
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
    marginTop: 15,
  },
});

export default styles;
